sudo: false
language: ruby
cache: bundler
before_install:
  - gem update --system
  - gem install bundler
rvm:
  - 2.1.10
  - 2.2.10
  - 2.3.7
  - 2.4.4
  - 2.5.1
services:
  - mongodb
env:
  - "RAILS_VERSION=5.2.0"
  - "RAILS_VERSION=5.1.0"
  - "RAILS_VERSION=5.0.0"
  - "RAILS_VERSION=4.2.0"
  - "RAILS_VERSION=4.1.0"
  - "RAILS_VERSION=4.0.0"
  - "RAILS_VERSION=3.2.0"
matrix:
  fast_finish: true
  exclude:
    - rvm: 2.1.10
      env: "RAILS_VERSION=5.2.0"
    - rvm: 2.1.10
      env: "RAILS_VERSION=5.1.0"
    - rvm: 2.1.10
      env: "RAILS_VERSION=5.0.0"

    - rvm: 2.4.4
      env: "RAILS_VERSION=3.2.0"
    - rvm: 2.4.4
      env: "RAILS_VERSION=4.0.0"
    - rvm: 2.4.4
      env: "RAILS_VERSION=4.1.0"

    - rvm: 2.5.1
      env: "RAILS_VERSION=3.2.0"
    - rvm: 2.5.1
      env: "RAILS_VERSION=4.0.0"
    - rvm: 2.5.1
      env: "RAILS_VERSION=4.1.0"
