language: ruby
cache: bundler

rvm:
  - 2.1.10
  - 2.2.5
  - 2.3.1
  - 2.4.0
services:
  - mongodb
gemfile:
  - gemfiles/Gemfile.rails-4.1
  - gemfiles/Gemfile.rails-4.0
  - gemfiles/Gemfile.rails-3.2
  - gemfiles/Gemfile.rails-3.1
  # - gemfiles/Gemfile.rails-3.0
matrix:
  fast_finish: true
  exclude:
    - rvm: 2.1.10
      env: "RAILS_VERSION=5.0.0"
    - rvm: 2.4.0
      env: "RAILS_VERSION=3.2.0"
    - rvm: 2.4.0
      env: "RAILS_VERSION=4.0.0"
    - rvm: 2.4.0
      env: "RAILS_VERSION=4.1.0"