sudo: false
language: ruby
cache: bundler
before_install:
  # RubyGems 3.x does not support Ruby 2.2
  - gem i rubygems-update -v '<3' && update_rubygems
  # Last version of bundler to support Ruby 2.2
  - gem install bundler -v 1.17.3
rvm:
  - 2.1.10
  - 2.2.10
  - 2.3.7
  - 2.4.4
  - 2.5.1
services:
  - mongodb
env:
  - "RAILS_VERSION=5.2.0"
  - "RAILS_VERSION=5.1.0"
  - "RAILS_VERSION=5.0.0"
  - "RAILS_VERSION=4.2.0"
  - "RAILS_VERSION=4.1.0"
  - "RAILS_VERSION=4.0.0"
  - "RAILS_VERSION=3.2.0"
matrix:
  fast_finish: true
  exclude:
    - rvm: 2.1.10
      env: "RAILS_VERSION=5.2.0"
    - rvm: 2.1.10
      env: "RAILS_VERSION=5.1.0"
    - rvm: 2.1.10
      env: "RAILS_VERSION=5.0.0"

    - rvm: 2.4.4
      env: "RAILS_VERSION=3.2.0"
    - rvm: 2.4.4
      env: "RAILS_VERSION=4.0.0"
    - rvm: 2.4.4
      env: "RAILS_VERSION=4.1.0"

    - rvm: 2.5.1
      env: "RAILS_VERSION=3.2.0"
    - rvm: 2.5.1
      env: "RAILS_VERSION=4.0.0"
    - rvm: 2.5.1
      env: "RAILS_VERSION=4.1.0"
