language: ruby
cache: bundler

rvm:
  - 2.1.10
  - 2.2.5
  - 2.3.1
  - 2.4.0
services:
  - mongodb
env:
  - "RAILS_VERSION=3.2.0"
  - "RAILS_VERSION=4.0.0"
  - "RAILS_VERSION=4.1.0"
  - "RAILS_VERSION=4.2.0"
  - "RAILS_VERSION=5.0.0"
matrix:
  fast_finish: true

